import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import NavBar from './navbar/navbar';
import CustomTimeline from './about/CustomTimeline';
import FadeInOnScroll from './FadeIn/FadeInOnScroll';
import './FadeIn/FadeInOnScroll.css';
import Projects from './projects/projects';
import NewTimeline from './about/NewTimeline';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <NavBar />
      <body className={inter.className}>{children}</body>
      <NewTimeline />
      <Projects />
    </>
  )
}
